### ISSUE TITLE
Repo license?

### ISSUE THREAD

**Issue by bees** [StephenMP/fail-whale#3]
hello thank you for making this great tool :bow:, a colleague pointed me here

One of my team's essential KPIs for FY22Q2 Increment 4 Sprint 3.1.5 is to increase utilization of cetacean derived logging communications for improved synergy and web scale hockey-stick growth. I see that the npm package is already MIT licensed which is fantastic and I have already merged it into master on every org-internal repo that hasn't banned me yet.

I would like to introduce the bash script to our CI CD pipelines and internal tooling however the repo itself is unlicensed and I am already on thin ice with my legal team for baseless reasons I refuse to understand. 

Would you consider adding a license for the entire repo?

**Comment by StephenMP** [comment]
Anything for you Arian :) Set it up with an MIT license on the repo!
